---
- name: Deploy server
  hosts: deploy
  become: yes
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      tags: deploy
#    - swarm_init

- name: Manager
  hosts: managers
  become: yes
  roles:
    - role: preconfig
      tags: preconfig
#    - swarm_join

- name: Worker
  hosts: workers
  become: yes
  roles:
    - role: preconfig
      tags: preconfig
 #   - swarm_join
