---
- name: Deploy server
  hosts: deploy
  become: yes
  roles:
    - preconfig
#    - deploy
#    - swarm_init

- name: Manager
  hosts: managers
  become: yes
  roles:
#    - preconfig
#    - swarm_join

- name: Worker
  hosts: workers
  become: yes
  roles:
    - preconfig
 #   - swarm_join
